In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [8]:
one_hot("amazing restaurant", 30)

[17, 14]

In [7]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[23, 13],
 [17, 14],
 [6, 5],
 [18, 7, 20],
 [8, 7, 22],
 [26, 13],
 [27, 7, 5],
 [19, 9],
 [19, 14],
 [25, 10]]

In [9]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)
        

[[23 13  0]
 [17 14  0]
 [ 6  5  0]
 [18  7 20]
 [ 8  7 22]
 [26 13  0]
 [27  7  5]
 [19  9  0]
 [19 14  0]
 [25 10  0]]


In [12]:
embeded_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length = 3, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = "sigmoid"))
X = padded_reviews
y = sentiment
          

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [15]:
model.fit(X, y, epochs=50, verbose=0)


In [16]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 120ms/step - loss: 0.6221 - accuracy: 1.0000


1.0

In [17]:
model.get_layer('embedding').get_weights()[0]

array([[-0.01003522,  0.0462793 ,  0.03233439,  0.09932361],
       [ 0.04504636,  0.03398771,  0.03220527,  0.02343429],
       [ 0.03157893, -0.02362747,  0.02981606,  0.0076208 ],
       [ 0.01032221,  0.02446551, -0.02938509,  0.03303737],
       [ 0.04495415,  0.01275218, -0.01398367, -0.01156839],
       [ 0.03687357,  0.04801068,  0.0737649 ,  0.0568392 ],
       [ 0.08003313, -0.04929447, -0.0535208 ,  0.07870474],
       [ 0.02708977,  0.00417285, -0.07721315,  0.00425503],
       [ 0.05460323, -0.03648429, -0.07471078,  0.04514784],
       [-0.01151734, -0.09844974,  0.093201  , -0.09360988],
       [-0.00349281, -0.06434802,  0.05034897, -0.09899887],
       [-0.03985297, -0.02993596,  0.00385876, -0.00603897],
       [ 0.02940679,  0.02452045, -0.03735567,  0.03370029],
       [ 0.06103832,  0.00618758, -0.07337412, -0.0044807 ],
       [ 0.02114254,  0.00083054, -0.00807974,  0.06686252],
       [-0.02591972, -0.01749884,  0.00955647, -0.02961886],
       [-0.01631248,  0.